name: Ship-it

on:
  push:
    branches: [ master, develop ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        # Fetch entire history. Required for chart-releaser; see https://github.com/helm/chart-releaser-action/issues/13#issuecomment-602063896
        fetch-depth: 0
    - name: Release Helm Chart
      # we depend on https://github.com/helm/chart-releaser-action/issues/12, which is not yet released
      uses: helm/chart-releaser-action@master
      with:
        charts_dir: .
      env:
        CR_TOKEN: "${{ secrets.CR_TOKEN }}"

  generate-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: helm-charts
    - name: Checkout helm-docs builder
      uses: actions/checkout@master
      with:
        repository: norwoodj/helm-docs
        path: helm-docs
        
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Build helm-docs builder
      working-directory: helm-docs/cmd/helm-docs
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go build   

    - name: Generate README docs for helm values
      working-directory: helm-charts
      run: ../helm-docs/cmd/helm-docs/helm-docs
    - name: Create PR
      uses: peter-evans/create-pull-request@v2
      with:
        title: Update helm values documentation
        commit-message: Generated for ${{ github.ref }}
        branch: update-helm-vulues-docs
        path: helm-charts
